import{a as $,S as P,i as s}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const R="50330405-e061f8fa8a72024873dc0b5e5",B="https://pixabay.com/api/",T=15;async function g(i,t=1){const a={key:R,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:T};return(await $.get(B,{params:a})).data}const p=document.querySelector(".gallery"),y=document.getElementById("global-loader"),h=document.querySelector(".js-btn"),b=document.querySelector(".loading-text"),A=new P(".gallery a",{captionsData:"alt",caption:!0,captionPosition:"bottom",captionDelay:250});//!=========================================================
function L(i){const t=i.map(({webformatURL:a,largeImageURL:l,tags:e,likes:o,views:c,comments:q,downloads:x})=>`<li class="gallery-item"><a class="gallery-link" href="${l}"><img class="gallery-img" src="${a}" alt="${e}"></a>
  <ul class="gallery-list">
    <li class="gallery-list-item"><b>likes</b>${o}</li>
  <li class="gallery-list-item"><b>views</b>${c}</li>
  <li class="gallery-list-item"><b>comments</b>${q}</li>
  <li class="gallery-list-item"><b>downloads</b>${x}</li>
  </ul>
</li>`).join("");p.insertAdjacentHTML("beforeend",t),A.refresh()}//!====================================================
function C(){p.innerHTML=""}function w(){y.classList.remove("hidden")}function S(){y.classList.add("hidden")}function I(){h.classList.remove("hidden")}function f(){h.classList.add("hidden")}function M(){b.classList.remove("hidden")}function O(){b.classList.add("hidden")}const v=document.querySelector(".form"),m=v.elements["search-text"];document.querySelector(".gallery");const _=document.querySelector(".js-btn");f();let u="",n=1,r=0;const N=15;v.addEventListener("submit",async i=>{if(i.preventDefault(),u=m.value.trim(),!u){s.info({message:"Будь ласка, введіть ключове слово!",position:"topRight",timeout:2e3,backgroundColor:"#ffa000"});return}n=1,C(),f(),w();try{const t=await g(u,n);if(!t.hits||t.hits.length===0){s.warning({title:"Warning",message:"Нічого не знайдено. Спробуйте інший запит!",position:"topRight",timeout:3e3,backgroundColor:"#ef4040"});return}L(t.hits),r=Math.ceil(t.totalHits/N),E(),d(),m.value=""}catch{s.error({title:"Error",message:"Сталася помилка. Спробуйте пізніше!",position:"topRight",timeout:3e3,backgroundColor:"#ffa040"})}finally{S()}});_.addEventListener("click",async()=>{n+=1,d(),w(),M();try{const i=await g(u,n);L(i.hits),j(),E(),d()}catch{s.error({title:"Error",message:"Не вдалося завантажити більше зображень!",position:"topRight",timeout:3e3,backgroundColor:"#ffa040"})}finally{S(),O()}});function d(){n<r?I():f()}function E(){n===1&&r>1&&s.info({message:`Було знайдено ${r} сторінок`,position:"topRight",timeout:2e3}),n===r&&r!==0&&s.info({message:"Ви завантажили всі дані",position:"topRight",timeout:2e3}),r===0&&s.error({message:"По вашому запиту нічого не знайдено",position:"topRight",timeout:2e3})}function j(){const i=document.querySelector(".gallery .gallery-item");if(i){const{height:t}=i.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
